config/routes.rb
Rails.application.routes.draw do

  root 'welcome#show'
  
  get 'rider_login', to: 'rider_sessions#new'
  post 'rider_login', to: 'rider_sessions#create'
  delete 'rider_logout', to: 'rider_sessions#destroy'
  
  get 'driver_login', to: 'driver_sessions#new'
  post 'driver_login', to: 'driver_sessions#create'
  delete 'driver_logout', to: 'driver_sessions#destroy'
  
  resources :riders, only: [:new, :create, :show]
  resources :drivers, only: [:new, :create, :show]
  resources :rides, only: [:new, :create, :update]
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  has_secure_password
  has_many :rides
  has_many :riders, through: :rides
  
  validates :name,
    presence: true
  validates :email,
    presence: true,
    uniqueness: true
  validates :phone_number,
    presence: true
  validates :password,
    presence: true, on: :create,
    confirmation: true
  validates :car_make,
    presence: true
  validates :car_model,
    presence: true
  validates :car_capacity,
    presence: true,
    numericality: { with: /\A[+-]?\d+\Z/ }
  validate :email_uniqueness

  def current_ride
    rides.where.not(status: "completed").last
  end
  
  def completed_rides
    rides.where(status: "completed")
  end
  
  private

  def email_uniqueness
    errors.add(:base, "Cannot use the same email as another user--must be unique") if matches_rider_email
  end
  
  def matches_rider_email
    Rider.any?{ |rider| rider.email == self.email }
  end
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :rider
  belongs_to :driver
  
  validates :pickup_location,
    presence: true
  validates :dropoff_location,
    presence: true
  validates :number_of_passengers,
    presence: true
  validates :status,
    presence: true
  validates :rider_id,
    presence: true
  
  def driver_name
    Driver.find(self.driver_id).name if self.driver_id
  end
  
  def rider_name
    Rider.find(self.rider_id).name if self.rider_id
  end
  
  def estimated_cost
    ((time_in_minutes.to_i / 3) * 2).round(2)
  end
  
  def cost
    (((self.dropoff_time - self.pickup_time) / 180 ) * 2 ).round(2)
  end
end

app/models/ride_estimator.rb
class RideEstimator
attr_reader :ride, :origin, :destination
  
  def initialize(ride, origin, destination)
    @ride = ride
    @origin = origin
    @destination = destination
  end
  
  def estimate
    ride.time_in_minutes = GoogleDirections.new(origin, destination).drive_time_in_minutes
    ride.mileage = GoogleDirections.new(origin, destination).distance_in_miles
  end
end

app/models/ride_updater.rb
class RideUpdater
attr_reader :ride, :driver
  
  def initialize(ride, driver)
    @ride = ride
    @driver = driver
  end
  
  def update
    if ride.status == "active"
      ride.driver_id = driver.id
      ride.status = "accepted"
      ride.accepted_time = DateTime.now
      ride.save
    elsif ride.status == "accepted"
      ride.status = "picked up"
      ride.pickup_time = DateTime.now
      ride.save
    else
      ride.status = "completed"
      ride.dropoff_time = DateTime.now
      ride.save
    end
  end
end

app/models/rider.rb
class Rider < ActiveRecord::Base
  has_secure_password
  has_many :rides
  has_many :drivers, through: :rides
  
  validates :name,
    presence: true
  validates :email,
    presence: true,
    uniqueness: true
  validates :phone_number,
    presence: true
  validates :password,
    presence: true
  validate :email_uniqueness
  
  def active_rides
    rides.where.not(status: "completed")
  end
  
  def completed_rides
    rides.where(status: "completed")
  end

  private

  def email_uniqueness
    errors.add(:base, "Cannot use the same email as another user--must be unique") if matches_driver_email
  end
  
  def matches_driver_email
    Driver.any?{ |driver| driver.email.downcase == self.email.downcase }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_rider,
                :current_driver,
                :current_driver_available_rides,
                :convert_to_readable
  
  def current_rider
    @current_rider ||= Rider.find(session[:rider_id]) if session[:rider_id]
  end
  
  def current_driver
    @current_driver ||= Driver.find(session[:driver_id]) if session[:driver_id]
  end
  
  def current_driver_available_rides
    Ride.where(status: "active").where("number_of_passengers <= ?", current_driver.car_capacity)
  end
  
  def convert_to_readable(datetime)
    datetime.strftime("%m/%d/%y at %I:%M %p")
  end
  
end

app/controllers/driver_sessions_controller.rb
class DriverSessionsController < ApplicationController

  def new
  end

  def create
    @driver = Driver.find_by(email: params[:session][:email])
    if @driver && @driver.authenticate(params[:session][:password])
      session[:driver_id] = @driver.id
      redirect_to @driver
    else
      flash[:message] = "Invalid login"
      render :new
    end
  end
  
  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :check_current_driver, only: [:show]  
  
  def new
    @driver = Driver.new
  end
  
  def create
    @driver = Driver.new(strong_driver_params)
    if @driver.save
      flash[:message] = "Successfully created account for #{@driver.name} as a driver"
      session[:driver_id] = @driver.id
      redirect_to @driver
    else
      flash.now[:errors] = @driver.errors.full_messages.join(", ")
      render :new
    end
  end
  
  def show
  end
  
  private
  
  def check_current_driver
    redirect_to root_path if !current_driver
  end
  
  def strong_driver_params
    params.require(:driver).permit(:name, :email, :phone_number, :password, :password_confirmation, :car_make, :car_model, :car_capacity)
  end
end

app/controllers/rider_sessions_controller.rb
class RiderSessionsController < ApplicationController
  
  def new
  end
  
  def create
    @rider = Rider.find_by(email: params[:session][:email])
    if @rider && @rider.authenticate(params[:session][:password])
      session[:rider_id] = @rider.id
      redirect_to @rider
    else
      flash[:message] = "Invalid login"
      render :new
    end
  end
  
  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  before_action :check_current_rider, only: [:show]
  
  def new
    @rider = Rider.new
  end
  
  def create
    @rider = Rider.new(strong_rider_params)
    if @rider.save
      flash[:message] = "Successfully created account for #{@rider.name} as a rider!"
      session[:rider_id] = @rider.id
      redirect_to @rider
    else
      flash.now[:errors] = @rider.errors.full_messages.join(", ")
      render :new
    end
  end
  
  def show
    
  end
  
  private
  
  def check_current_rider
    redirect_to root_path if !current_rider
  end
  
  def strong_rider_params
    params.require(:rider).permit(:name, :email, :phone_number, :password, :password_confirmation)
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  
  def new
    @ride = Ride.new
  end
  
  def create
    @ride = Ride.new(strong_ride_params)
    @ride.rider_id = current_rider.id
    RideEstimator.new(@ride, params[:ride][:pickup_location], params[:ride][:dropoff_location]).estimate
    if @ride.save
      flash[:message] = "You've just requested a ride!"
      redirect_to rider_path(current_rider)
    else
      flash.now[:errors] = @ride.errors.full_messages.join(", ")
    end
  end
  
  def update
    ride = Ride.find(params[:id])
    RideUpdater.new(ride, current_driver).update
    redirect_to driver_path(current_driver)
  end
  
  private

  def strong_ride_params
    params.require(:ride).permit(
      :pickup_location,
      :dropoff_location,
      :number_of_passengers,
      :status,
      :requested_time,
      :accepted_time,
      :pickup_time,
      :dropoff_time,
      :rider_id,
      :driver_id,
      :time_in_minutes,
      :mileage
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/driver_sessions/new.html.erb
<div class="container">
  <h1>Login</h1>

  <%= form_for :session do |f| %>
    <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Login as Driver", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/drivers/_available_rides.html.erb
<div class="available-rides">
  <h3>Available Rides:</h3>
  <div>
    <% current_driver_available_rides.each do |ride| %>
      <div class="current-available-rides">
        <%= ride.pickup_location %>
        <br>
        to
        <br>
        <%= ride.dropoff_location %>
        <br>
        <div class="passenger-count">
          <%= ride.number_of_passengers %> passengers
        </div>
        <br>
        <div class="claim-button">
          <%= link_to "Claim Ride", ride_path(ride), method: :put, class: "btn btn-default btn-md" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/drivers/_completed_rides.html.erb
<div id="completed-rides">
  <h2>Completed Rides: <%= current_driver.completed_rides.count %></h2>
  <% current_driver.completed_rides.each do |ride| %>
    <div class="completed-rides-info">
      Rider: <%= ride.rider_name %>
      <br>
      Driver: <%= ride.driver_name %>
      <br>
      Pickup Location: <%= ride.pickup_location %>
      <br>
      Dropoff Location: <%= ride.dropoff_location %>
      <br>
      Requested Time: <%= convert_to_readable(ride.created_at) %>
      <br>
      Accepted Time: <%= convert_to_readable(ride.accepted_time) %>
      <br>
      Pick-up Time: <%= convert_to_readable(ride.pickup_time) %>
      <br>
      Completed Time: <%= convert_to_readable(ride.dropoff_time) %>
      <br>
      Ride Cost: <%= number_to_currency(ride.cost, unit: "$") %>
    </div>
  <% end %>
</div>

app/views/drivers/_current_ride.html.erb
<div id="current-ride">
  <h3>Current Ride:</h3>
  <%= current_driver.current_ride.pickup_location %>
  <br>
  to
  <br>
  <%= current_driver.current_ride.dropoff_location %>
  <br>
  <div id="current-ride-status">
    Ride Status: <%= current_driver.current_ride.status %>
  </div>
  <br>
  <div id="current-ride-button">
    <% if current_driver.current_ride.status == "accepted" %>
      <%= link_to "Pick up Rider", ride_path(current_driver.current_ride), method: :put, class: "btn btn-default btn-md" %>
    <% elsif current_driver.current_ride.status == "picked up" %>
      <%= link_to "Complete Ride", ride_path(current_driver.current_ride), method: :put, class: "btn btn-default btn-md" %>
    <% end %>
  </div>
</div>

app/views/drivers/_form.html.erb
<%= form_for driver do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone Number" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :car_make, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :car_make, class: "form-control", placeholder: "Car Make" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :car_model, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :car_model, class: "form-control", placeholder: "Car Model" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :car_capacity, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :car_capacity, class: "form-control", placeholder: "Car Capacity" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Sign Up!", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/drivers/new.html.erb
<div class="container">
  <h1>Sign up as a Driver!</h1>

  <%= render partial: "form", locals: { driver: @driver } %>
</div>

app/views/drivers/show.html.erb
<h1>Welcome, <%= current_driver.name %>!</h1>

<% if !current_driver.current_ride %>
  
  <%= render partial: "available_rides" %>
  
<% else %>
  
  <%= render partial: "current_ride" %>
  
<% end %>

<%= render partial: "completed_rides" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalAssessment</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Goober</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_rider %>
          <li class="active">
            <%= link_to "Logout", rider_logout_path, method: :delete, class: "navbar-link" %>
          </li>
        <% elsif current_driver %>
          <li class="active">
            <%= link_to "Logout", driver_logout_path, method: :delete, class: "navbar-link" %>
          </li>
        <% else %>
          <li class="active">
            <%= link_to "Login as Rider", rider_login_path, class: "navbar-link" %>
          </li>
          <li class="active">
            <%= link_to "Login as Driver", driver_login_path, class: "navbar-link" %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= flash[:message] %>
<%= flash.now[:errors] %>

<%= yield %>

</body>
</html>

app/views/rider_sessions/new.html.erb
<div class="container">
  <h1>Login</h1>
  
  <%= form_for :session do |f| %>
    <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :email, class: "col-sm-10 form-control", placeholder: "Email" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Login as Rider", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/riders/_active_ride_requests.html.erb
<div id="active-ride-requests">
<h2>Active Ride Requests:</h2>
<div id="active-rides">
  <% current_rider.active_rides.each do |ride| %>
    <div class="active-ride-info">
      Requested Time: <%= convert_to_readable(ride.created_at) %>
      <br>
      Ride Duration: <%= pluralize(ride.time_in_minutes, "minute") %>
      <br>
      Ride Distance: <%= pluralize(ride.mileage, "mile") %>
      <br>
      Estimated Cost: <%= number_to_currency(ride.estimated_cost) %>
      <% if ride.driver %>
        <br>
        Your Driver: <%= ride.driver.name %> (<%= ride.driver.car_make %> <%= ride.driver.car_model %>)
      <% end %>
      <br>
      Ride Status: <%= ride.status %>
    </div>
  <% end %>
</div>
</div>

app/views/riders/_available_rides.html.erb
<div class="available-rides">
  <%= link_to "Request a Ride", new_ride_path, class: "btn btn-default btn-lg" %>
  <h2>Active Ride Requests: None</h2>
</div>

app/views/riders/_completed_rides.html.erb
<div id="completed-rides">
  <h2>Completed Rides (<%= current_rider.completed_rides.count %>)</h2>
    <% current_rider.completed_rides.each do |ride| %>
      <div class="completed-rides-info">
        Rider: <%= ride.rider_name %>
        <br>
        Driver: <%= ride.driver_name %>
        <br>
        Pickup Location: <%= ride.pickup_location %>
        <br>
        Dropoff Location: <%= ride.dropoff_location %>
        <br>
        Requested Time: <%= convert_to_readable(ride.created_at) %>
        <br>
        Accepted Time: <%= convert_to_readable(ride.accepted_time) %>
        <br>
        Pick-up Time: <%= convert_to_readable(ride.pickup_time) %>
        <br>
        Completed Time: <%= convert_to_readable(ride.dropoff_time) %>
        <br>
        Ride Cost: <%= number_to_currency(ride.cost, unit: "$") %>
      </div>
    <% end %>
</div>

app/views/riders/_form.html.erb
<%= form_for rider do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone Number" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Sign Up!", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/riders/new.html.erb
<div class="container">
  <h1>Sign up as Rider</h1>

<%= render partial: "form", locals: {rider: @rider} %>

</div>

app/views/riders/show.html.erb
<div class="container">
  <h1 id="rider-welcome">Welcome, <%= current_rider.name %>!</h1>

  <% if current_rider.active_rides.length == 0 %>
  
    <%= render partial: "available_rides" %>
  
  <% else %>
  
    <%= render partial: "active_ride_requests" %>
  
  <% end %>

  <%= render partial: "completed_rides" %>
</div>

app/views/rides/new.html.erb
<div class="container">
  <h1>Tell us about your ride:</h1>

  <%= form_for @ride do |f| %>
    <div class="form-group">
      <%= f.label :pickup_location, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :pickup_location, class: "form-control", placeholder: "Pickup Location" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :dropoff_location, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :dropoff_location, class: "form-control", placeholder: "Dropoff Location" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.label :number_of_passengers, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :number_of_passengers, class: "form-control", placeholder: "Number of Passengers" %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Request Ride", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/welcome/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to Goober!</h1>
    <h3>Sign me up as a...</h3>
    <div id="buttons">
    <%= link_to "Rider",  new_rider_path, class: "btn btn-primary btn-lg signup-button" %>
    <%= link_to "Driver", new_driver_path, class: "btn btn-primary btn-lg signup-button" %>
    </div>
  </div>
</div>